name: CodeCov Coverage

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run coverage
        run: go test -coverprofile=coverage.out -covermode=count ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
